services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - MAX_CONNECTIONS=100
      - SHARED_BUFFERS=256MB
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres
    command: flask run --host 0.0.0.0 --port 8080

volumes:
  pgdata: {}